### ISSUE TITLE
Plan: Categories Page

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/TIY-Catalog#5]
### Basic Plan
- [ ] Main Section - 4 columns, evenly spaced
  - [ ] Left Column
    - [ ] Categories - Heading
    - [ ] Refining Search - Heading
      - [ ] Type
      - [ ] Price
      - [ ] Color
      - [ ] Order Options
      - [ ] Shop Location
      - [ ] Ships To
  - [ ] Right Column (3)
    - [ ] Left top box
      - [ ] What category
      - [ ] result amount
    - [ ] Right top box - select
      - [ ] sort (Most Recent, *Relevancy, Highest Price, Lowest Price)
    - [ ] Listings evenly spaced in 3 columns
      - [ ] One listing
        - [ ] Image
        - [ ] Description - Brief
        - [ ] Shop - link, Price
      - [ ] One Listing: Hover
        - [ ] Right corner
          - [ ] Heart - Favorite
          - [ ] Hamburger Menu - Add to user lists, can 
          - [ ] create a new list
      - [ ] One Listing: Hover (extended)
        - [ ] Detailed description
  - [ ] Bottom
    - [ ] Links to  relevant shops
    - [ ] Previous arrow, pages, next arrow
### Static vs. Placeholder
- [ ] Items that are static
  - [ ] grid columns/size
  - [ ] Sort By Select box (right side)
  - [ ] Show Results for box
  - [ ] All categories
  - [ ] Refine your search box
  - [ ] Item type
  - [ ] Price
  - [ ] Color
  - [ ] Ordering options
  - [ ] Locations
  - [ ] Ships to
- [ ] Items that change (placeholder)
  - [x] Grid
  - [ ] Item images
  - [ ] Item names
  - [ ] Item prices
  - [ ] What path you took
  - [ ] How many results were returned
  - [ ] Show Results For
  - [ ] Current category 
  - [ ] Child Categories

**Comment by JessyRiordan** [comment]
![category-main](https://cloud.githubusercontent.com/assets/12103371/8209525/58099596-14db-11e5-9a2e-44459d3d962b.png)

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-Catalog/pull/5
