### ISSUE TITLE
Plan: Products Page

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/TIY-Catalog#6]
### Basic Plan
- [x] Header
  - [x] Shop Image - Square
  - [x] Shop Name - Under - Heart button Favorite Shop
  - [x] right side images that navigate to other products of that shop
  - [x] total shop items (listings)
- [ ] Body
  - [ ] Column 1
    - [ ] Favorite for the listing
    - [ ] Explanation for favorites
    - [x] Image
      - [x] Arrows - grey
      - [ ] On image
      - [x] Left side hover - blue arrow
      - [x] right side hover - blue arrow
- [ ] Box with thumbnails of all images - first image is active
- [ ] all other greyed out 
- [x] Zoom
- [ ] Shop Image
- [ ] Link to request a custom order
- [ ] Three Tabs
- [ ] Tab One - Item Details
- [ ] contains item details
- [ ] Tab Two - Star rating
- [ ] with stars
- [ ] number of reviews
- [ ] all reviews
- [ ] Tab Three - Shipping and Policies for shop
- [ ] Column 2
- [ ] Box 1
- [ ] Item name
- [ ] Price w/ currency
- [ ] Ask a Question button
- [ ] Option Possibilities  (based on product)  
- [ ] Quantity -or- single item -or- # available
- [ ] Color
- [ ] Size
- [ ] Overview - bulleted list, feedback link, favorited by link
- [x] Does the shop accept gift cards?
- [x] Big green add to cart button  
- [ ] Box 2
- [x] Favorite button for the item
- [ ] hamburger menu - add to list
- [ ] social media
- [ ] Box 3
- [x] Shop Image
- [ ] Shop Name
- [ ] Shop Location
- [x] 2 columns of products
- [x] mage, name, price
### Stay vs. Placeholders

Items that stay the same

Header
Favorite shop button
4 images (other items)
1 items box (just visual)
Image
Left/Right click arrows
Zoom option
Possible thumbnails
Item info
Three tabs
Item Detail title 
Star visual
Shipping & Policies
Column 2
Ask a question
Feedback and Favorited by (what pops will change)
Add to Cart Button
Favorited and menu button
Social media tab
Grid for shop (outline only)

Item details that change

Header 
Shop icon
Other items 
Number of items
Main image
smaller thumbnails
Item 
Info
Star rating / how many reviews
Shipping policy specifics
Item name
Item price
Item quantity (if applicable)
Item options
Item overview
Shop
Icon
Name

**Comment by JessyRiordan** [comment]
![product-main-top](https://cloud.githubusercontent.com/assets/12103371/8209581/b245483e-14db-11e5-98e3-f6f288ce75ed.png)

**Comment by JessyRiordan** [comment]
![product-main-bottom](https://cloud.githubusercontent.com/assets/12103371/8209596/c6569f80-14db-11e5-94cd-40b0fcbef6d0.png)

**Comment by JessyRiordan** [comment]
![product-hover](https://cloud.githubusercontent.com/assets/12103371/8209616/e396820e-14db-11e5-9db4-f30f82db593b.png)

**Comment by MStaehling** [comment]
https://github.com/MStaehling/TIY-Catalog/pull/5
